deployments:
  deploymentGating:
    enabled: true # to enable the feature
    retry: 50 # run poll action 50 times
    sleep: 30 # wait 30 seconds between each poll
    environments: # select the environments you'd like to use with this feature
    - Production
  services:
    ids:
    - b:YXJpOmNsb3VkOmdyYXBoOjpzZXJ2aWNlLzcyODgyY2Q0LWVlMGItMTFlYS1iNmFlLTEyOGI0MjgxOTQyNC80NjRjYmU2MC1iMzE4LTExZWYtOTkwMS0xMjAxZjE2ZWQ0MWY=
